tp_core_homepage:
    path:     /
    defaults: 
        _controller: TPCoreBundle:Core:index 
        
tp_core_contact:
    path:     /Contact
    defaults: 
        _controller: TPCoreBundle:Core:contact 